name: mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5 # For state management
  intl: ^0.18.1    # For date formatting
  image_picker: ^0.8.4+3 #image
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.4
  firebase_core: ^3.6.0
  get: ^4.6.6
  flutter_local_notifications: ^12.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets section for images or other assets
  assets:
    - assets/images/
